name: LivingAnalysis
channels:
  - conda-forge
dependencies:
  - python=3.*
  - ipython=7.10.*
  - jupyterlab=3.*
  - scipy
  - numpy
  - pandas
  - geopandas
  - geopy
  - geojson
  - matplotlib
  - folium
  - networkx
  - osmnx
  - rasterio
  - richdem
  - rasterstats
  - contextily
